<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp
 * @copyright   Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<title><?php echo $this->getTitle(); ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<meta charset="utf-8">
<link rel="canonical" href="<?php echo $this->helper('pramp')->getCanonicalUrl(); ?>" />
<link rel="amphtml" href="<?php echo $this->helper('pramp')->getAmpUrl(); ?>" />
<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">

<?php
//Include Google fonts character subsets (such as extended latin, cyrillic)
$theme = Mage::helper('porto');
$charSubset = '&subset=latin';
$d = $theme->getCfgSectionDesign();
if (isset($d['font']['primary_char_latin_ext']) && $d['font']['primary_char_latin_ext'] == 1)
    $charSubset .= ',latin-ext';
if (isset($d['font']['custom_char_subset']) && $d['font']['custom_char_subset'])
    $charSubset .= ',' . $d['font']['custom_char_subset'];
?>
<?php if ($d['font']['custom'] && $d['font']['primary_font_family_group'] == 'google'): ?>
    <link rel="stylesheet" href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $d['font']['primary_font_family']);
    echo $charSubset; ?>' type='text/css' />

<?php else: ?>
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans%3A300%2C300italic%2C400%2C400italic%2C600%2C600italic%2C700%2C800%2C800italic&amp;v1&amp;subset=latin%2Clatin-ext" type="text/css" media="screen"/>
<?php endif; ?>

<!--<script src="<?php echo $this->getSkinUrl('js/jquery-1.10.2.min.js') ?>"></script>-->
<?php echo $this->getChildHtml('ogtags') ?>
<?php echo $this->getChildHtml('ldjson') ?>
<?php echo $this->getChildHtml('algolia-polyfill') ?>
<?php echo $this->getChildHtml('beforetopsearch') ?>
<?php // echo $this->getCssJsHtml()  ?>
<?php // echo $this->getChildHtml()  ?>
<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style>
<style amp-custom type="text/css">
<?php echo $this->getChildHtml('ampcss') ?>
</style>
<!-- <?php echo strrev('pmA_tekcormulP egakcap@ .sliated esnecil rof ALUE/ikiw/ten.tekcormulp.ikiw//:ptth eeS .devreser sthgir llA .cnI tekcormulP 6102 thgirypoC') ?> -->
<noscript>
<style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style>
</noscript>

<?php echo $this->getChildHtml('ampjs') ?>
<link type="text/css" rel="stylesheet" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . ('smartwave/jquery/jquery-ui-1.10.4.min.css') ?>">
<link type="text/css" rel="stylesheet" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . ('smartwave/jquery/plugins/owl-carousel/owl.carousel.css') ?>">
<link type="text/css" rel="stylesheet" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . ('smartwave/jquery/plugins/owl-carousel/owl.theme.css') ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/plumrocket/local.css') ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('algoliasearch/algoliasearch.css') ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('megamenu/css/font-awesome.min.css') ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('icons/css/porto.css') ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('megamenu/css/megamenu.css') ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/plumrocket/custom.css') ?>">
<script src="<?php echo $this->getSkinUrl('js/jquery-1.10.2.min.js') ?>"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . ('prototype/prototype.js') ?>"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . ('prototype/validation.js') ?>"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . ('scriptaculous/slider.js') ?>"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . ('varien/form.js') ?>"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . ('mage/cookies.js') ?>"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . ('smartwave/jquery/jquery.cookie.js') ?>"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . ('smartwave/jquery/jquery-ui-1.10.4.min.js') ?>"></script>
 
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . ('smartwave/jquery/plugins/owl-carousel/owl.carousel.min.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('js/customscript.js') ?>"></script> 
