<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp
 * @copyright   Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php
    $categories = $this->helper('pramp/homepage')->getTopLevelCategories();
    $mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/category/';
    $defaultImage = $this->getSkinUrl('images/plumrocket/pramp/photos/homepage-default.png');
    $imageWidth = 380;
    $imageHeight = 140;
?>
<div class="col-main">
    <div class="std">
        <div class="amp-cat">
            <?php foreach ($categories as $_category): ?>
                <a href="<?php echo $_category->getUrl(); ?>">
                    <span>
                        <?php
            	            $ampHomeImage = $_category->getData('amp_homepage_image');
            	            $imgUrl = $ampHomeImage ? $mediaUrl . $ampHomeImage : $defaultImage;
                            $cropHeight = min($imageWidth / 1.5, $imageHeight);
                            $cropWidth = $cropHeight * 1.5;
                        ?>
                        <amp-img layout="responsive" src="<?php echo  $imgUrl; ?>"
                            alt="test" height="<?php echo $cropHeight; ?>" width="<?php echo $cropWidth; ?>"></amp-img>
                        <span><?php echo $_category->getName() ?></span>
                    </span>
                </a>
            <?php endforeach; ?>
        </div>
    </div>
</div>