<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Amp
 * @copyright   Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

$_product = $this->getProduct();
$_msrpPrice = "";
?>

<div class="price-box map-info">
    <?php if (!Mage::helper('pramp')->isAmpRequest()) : ?>
        <?php $_price = $this->helper('tax')->getPrice($_product, $_product->getMsrp()) ?>
        <?php if ($_product->getMsrp()): ?>
            <?php $_msrpPrice = $this->helper('core')->currency($_product->getMsrp(),true,true) ?>
            <span class="old-price" id="product-price-<?php echo $_product->getId() ?><?php echo $this->getIdSuffix() ?>"><?php echo $_msrpPrice ?></span>
        <?php endif; ?>
        <?php $helpLinkId = 'msrp-click-' . $_product->getId() . $this->helper('core')->getRandomString(20); ?>
        <a href="#" class="map-link" id="<?php echo($helpLinkId);?>"><?php echo $this->__('Click for price') ?></a>
        <script type="text/javascript">
            <?php if ($this->helper('catalog')->isShowPriceOnGesture($_product)): ?>
                var newLink = Catalog.Map.addHelpLink(
                        $('<?php echo $helpLinkId ?>'),
                        "<?php echo $this->escapeHtml($_product->getName()) ?>",
                        <?php echo $this->getRealPriceJs($_product) ?>,
                        '<?php echo $_msrpPrice ?>',
                        "<?php echo $_product->isSalable() ? $_product->getAddToCartUrl() : '' ?>"
                );
                newLink.product_id = '<?php echo $_product->getId() ?>';
            <?php else: ?>
                Catalog.Map.addHelpLink(
                        $('<?php echo $helpLinkId ?>'),
                        "<?php echo $this->escapeHtml($_product->getName()) ?>",
                        null,
                        null,
                        "<?php echo $_product->getProductUrl() ?>"
                );
            <?php endif; ?>
        </script>
    <?php else : ?>
        <span class="price">Hidden price!</span>
    <?php endif; ?>
</div>