<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<?php if($meta_title=$this->getMetaTitle()): ?>
<title><?php echo htmlspecialchars($meta_title) ?></title>
<?php else: ?>



<?php if (Mage::registry('current_category') && (!Mage::registry('product')))
    {
//get category ids of product to check show logo category
$baby_catid = Mage::getStoreConfig("legenda_setting/general_settings/baby_catid");
$g_shock_catid = Mage::getStoreConfig("legenda_setting/general_settings/gshock_catid");
$kids_id = Mage::getStoreConfig("legenda_setting/general_settings/kids_catid"); 
$cat_idd = Mage::registry('current_category')->getParentCategory()->getId(); 
$cat_parent_name = Mage::registry('current_category')->getParentCategory()->getName(); //get parent name
$txt_name = str_replace("Watches", " ", $cat_parent_name); // thay the watches bang ky tu trong
// if parent cat is baby or shock will add new text = Watches
   if (($cat_idd == $baby_catid) || ($cat_idd == $g_shock_catid)){
        $title = $txt_name.$this->getTitle() . " Watches"; 
           }else if($cat_idd == $kids_id){
                  $title = $this->getTitle() . " Watches";
           }
           else{
               $title = $this->getTitle();
           }

   }
   else
       {
       $title = $this->getTitle();  // nguoc lai th de nguyen
            }
   
?>
<title class="fgc"><?php //echo $this->getTitle(); ?><?php if (Mage::registry('current_category') && (!Mage::registry('product'))) : echo $title." | BuyWatchesOnline.com.au"; else: echo $title;  endif; ?></title>
<?php endif; ?>
<?php if (strpos(Mage::getBaseUrl(),'buygoodsonline.com.au') !== false): ?>
<meta name="google-site-verification" content="avV8CKyIHBz3iPJCWUbzNO-cv7wpUecAfxz7PzPFoGU" />
<?php endif; ?>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<?php if (Mage::app()->getStore()->getCode() == 'casio_english'):?>
    <meta name="google-site-verification" content="HRikwp7f4Kbx7RVdNuiGjGUFrNMSmiQBBP6aKypeMH4" />
<?php endif;?>
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<?php //Include Google fonts character subsets (such as extended latin, cyrillic)
    $theme = Mage::helper('porto');
    $charSubset = '&subset=latin';
    $d = $theme->getCfgSectionDesign();
    if (isset($d['font']['primary_char_latin_ext']) && $d['font']['primary_char_latin_ext']==1 )
        $charSubset .= ',latin-ext';
    if (isset($d['font']['custom_char_subset']) && $d['font']['custom_char_subset'])
        $charSubset .= ','.$d['font']['custom_char_subset'];
?>
<?php if ($d['font']['custom'] && $d['font']['primary_font_family_group'] == 'google'): ?>
<link rel="stylesheet" href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $d['font']['primary_font_family']); echo $charSubset; ?>' type='text/css' />

<?php else: ?>
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans%3A300%2C300italic%2C400%2C400italic%2C600%2C600italic%2C700%2C800%2C800italic&amp;v1&amp;subset=latin%2Clatin-ext" type="text/css" media="screen"/>
<?php endif;?>
<link href='//fonts.googleapis.com/css?family=Shadows+Into+Light|Carter+One' rel='stylesheet' type='text/css'/>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
<script type="text/javascript">
    wow = new WOW(
      {
        animateClass: 'animated',
        offset:       100
      }
    );
    wow.init();
</script>
<!--<?php echo "Porto Magento Theme: v".Mage::getConfig()->getModuleConfig("Smartwave_Porto")->version; ?>-->