<?php
/**
 * Created by PhpStorm.
 * User: svatoslavzilicev
 * Date: 16.06.16
 * Time: 17:34
 */
?>
<div class="hometopimgs">
    <div class="imageitem" style="float: left">
        <a href="/women-s-watches.html">
            <img src="<?php echo $this->getSkinUrl('images/home/mock_03.jpg') ?>"/>
        </a>
    </div>
    <div class="imageitem" style="float: right">
        <a href="/men-s-watches.html">
            <img src="<?php echo $this->getSkinUrl('images/home/mock_05.jpg') ?>"/>
        </a>
    </div>
    <div style="clear: both"></div>
</div>
<div class="bottomline"></div>
<div class="watchbrands">
    <div class="branditem">
        <a href="">
            <img src="<?php echo $this->getSkinUrl('images/home/mock_10.jpg') ?>"/>
        </a>
    </div>
    <div class="branditem" style="margin: 0 3%">
        <a href="">
            <img src="<?php echo $this->getSkinUrl('images/home/mock_12.jpg') ?>"/>
        </a>
    </div>
    <div class="branditem">
        <a href="/casio-g-shock.html">
            <img src="<?php echo $this->getSkinUrl('images/home/mock_14.jpg') ?>"/>
        </a>
    </div>
</div>