<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_showcartbutton = Mage::getStoreConfig('porto_settings/category_grid/show_addtocart', $code);
    $_showcartbutton = Mage::getStoreConfig('porto_settings/category_grid/show_addtolinks', $code);
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
    //var_dump($_category);
?>
<!--add by fgc-->
<?php
//get category ids of product to check show logo category
$baby_catid = Mage::getStoreConfig("legenda_setting/general_settings/baby_catid");
$g_shock_catid = Mage::getStoreConfig("legenda_setting/general_settings/gshock_catid");
$kids_id = Mage::getStoreConfig("legenda_setting/general_settings/kids_catid"); 
//echo $kids_id;
//$cat_ids = $_product->getCategoryIds();
$gshock_catid = $_helper->categoryAttribute($_category, $_category->getId(), 'gshock_catid');
$gbaby_catid = $_helper->categoryAttribute($_category, $_category->getId(), 'baby_catid');
//$boys_id = $_helper->categoryAttribute($_category, $_category->getId(), 'parent_id');//1698;


//processing string
$cat_idd = $this->getCurrentCategory()->getParentCategory()->getId(); //get parent category
$cat_parent_name = $this->getCurrentCategory()->getParentCategory()->getName(); //get parent name
$txt_name = str_replace("Watches", "", $cat_parent_name);
$txt = $_helper->categoryAttribute($_category, $_category->getName(), 'name');
//$txt_add = substr_replace($txt, ' Digital', strlen($txt)-8, 0);
$txt_add = $txt_name .$txt. " Watches"; 
$txt_add_kids = $txt. " Watches"; 
        



?>
<div class="page-title category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
        
<!--  <h1 class="name-cat" id_cat="<?php //echo $gshock_catid ?>"><?php //echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>-->
        <?php  if ($g_shock_catid == $cat_idd) {?>
            <h1 class="name-cat cat1" id_cat="<?php echo $gshock_catid ?>"><?php echo $txt_add ?></h1>
        <?php //G shock ?>
          <?php }else if ($baby_catid == $cat_idd ) {?>
            <h1 class="name-cat cat2" id_cat="<?php echo $gshock_catid ?>"><?php echo $txt_add ?></h1>
       <?php }else if ($kids_id == $cat_idd ) {?>
             <h1 class="name-cat cat3" id_cat="<?php echo $gshock_catid ?>"><?php echo $txt_add_kids ?></h1>
        
        <?php }else{?>
            <h1 class="name-cat cat4" id_cat="<?php echo $gshock_catid ?>"><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
        <?php }?>
       
</div>

<div id="brand-logo">
    <?php  if ($g_shock_catid ==$gshock_catid  ) {?>
    <img src="<?php echo Mage::getBaseUrl() . 'skin/frontend/smartwave/portowatch/images/casio/banner_gshock_site.jpg'; ?>" alt="<?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name'); ?>"/>
      <?php }//G shock ?>
   
            <?php  if ($baby_catid ==$gbaby_catid  ) {?>
    <img src="<?php echo Mage::getBaseUrl() . 'skin/frontend/smartwave/portowatch/images/casio/banner_babyg_site.jpg'; ?>" alt="<?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name'); ?>"/>
      <?php }//Baby shock ?>
</div>

<div class="clearfix"></div>
<!---end add-->
<?php if($_description = $_category->getDescription()): ?>
    <div class="category-description">
        <p><?php echo $_description; ?></p>
    </div>
<?php endif; ?>

<?php echo $_imgHtml ?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>



  