@font-face{
font-family:font-icon;
src:url(<?php echo $this->getAmpSkinUrl('css/plumrocket/pramp/icon.ttf') ?>);
}

<?php
$navigationsTextColor = $this->helper('pramp')->getNavigationsTextColor();
$linkColor = $this->helper('pramp')->getLinkColor();
$linkColorHover = $this->helper('pramp')->getLinkColorHover();
$priceTextColor = $this->helper('pramp')->getPriceTextColor();
$logoWidth = $this->helper('pramp')->getLogoWidth();
$buttonBgColor = $this->helper('pramp')->getButtonBgColor();
$buttonTextColor = $this->helper('pramp')->getButtonTextColor();
?>

body{margin:0;padding:0;font-family:"Helvetica Neue",Verdana,Arial,sans-serif}

<?php if ($this->helper('pramp')->getRtlEnabled()) { ?>
body{direction:rtl;unicode-bidi:embed;}
<?php } ?>

body,button,input,select,table,textarea{color:#636363;font-size:14px;line-height:1.5}
a{color:<?php echo $linkColor ?>;text-decoration:none}
a:hover{color:<?php echo $linkColorHover ?>;text-decoration:underline}
a:focus{outline:none;color:#143d52}
ol,ul{list-style:none;margin:0;padding:0}
.desktop{display:block}
.clearfix:before,.clearfix:after{content:"";display:block;clear:both}
@media (max-width:770px){
.desktop{display:none}
}

h1,.h1,h2,.h2,h3,.h3,h4,.h4,h5,.h5,h6,.h6{margin:0;font-family:"Raleway","Helvetica Neue",Verdana,Arial,sans-serif;font-style:normal;line-height:1.2;text-transform:uppercase;font-weight:400;color:#636363;margin-bottom:0.5em}
h1,.h1{font-size:21px}
h2,.h2{font-size:18px}
h3,.h3{font-size:16px}
h4,.h4{font-size:14px}
h5,.h5{font-size:13px}
h6,.h6{font-size:12px}
.icon{font-family:font-icon;font-size:19px}
.page{position:relative;max-width:1260px;margin:0 auto;padding:10px 0}
button{background:<?php echo $buttonBgColor  ?>;display:inline-block;padding:7px 15px;border:0;color:<?php echo $buttonTextColor ?> ;font-size:13px;line-height:normal;text-transform:uppercase;margin:10px 0 0 0}

.notice-inner{background:#676157;color:#e6e6e6;font-size:11px;line-height:14px;padding:14px 10px;box-sizing:border-box}
.notice-inner p{margin:0}
@media (min-width:771px){
.header-container{padding:0 30px;position:relative}
}

@media (max-width:771px){
.notice-inner{padding:4px 10px; font-size:10px; line-height:12px}
}

.logo{display:block;padding:10px;max-width:<?php echo $logoWidth; ?>px}
h1.logo{padding:0; margin-bottom:0}
.header strong{display:none}

.nav-primary a{text-decoration:none;position:relative;display:block;color:<?php echo $navigationsTextColor ?>;line-height:30px;padding:3px;font-family:"Raleway","Helvetica Neue",Verdana,Arial,sans-serif}
.nav-primary>li>a{padding:0 25px}
.nav-primary a:hover{color:<?php echo $navigationsTextColor  ?>}
.nav-primary li{position:relative}
.nav-primary li.level1 a{border-bottom:1px solid #cccccc}
.nav-primary li.level1.parent > a:after{content:'';width:0;height:0;position:absolute;right:7px;border-width:5px 0 5px 5px;border-color:transparent transparent transparent <?php echo $navigationsTextColor ?>;border-style:solid;top:50%;margin-top:-6px}
.nav-primary li.level1:last-child a,.nav-primary li.level2:last-child a{border-bottom:0}
.nav-primary li.level0 > a{text-transform:uppercase}

@media (min-width:771px){
#nav{display:block; border-bottom:1px solid #ededed; margin-top:15px}
a.level0{padding:0 25px}
li.level0,#nav a.level0{display:inline-block}
li.level0 ul{background:#FBFBFB;border:solid 1px #cccccc;position:absolute;left:0;top:30px;z-index:10;width:250px;padding-left:10px;padding-right:10px;display:none}
li.level0 ul ul{position:static}
li.level0 li:hover > ul{display:block}
.dir-rtl li.level0 ul{left:auto;right:0}
#nav li.level0:hover > ul{display:block}
}
@media (max-width:770px){
.skip-links li a:hover{background-color:#f4f4f4; text-decoration:none}
a.logo{margin-left:10px;max-width:35%}
}

@media (max-width:640px){
}

.acc-cwrap{position:absolute;top:0;right:30px}
.dir-rtl .acc-cwrap{right:auto;left:30px}
.acc-cwrap .skip-link .label{font-size:14px;text-transform:uppercase}
.acc-cwrap .skip-link{padding:0 10px;color:<?php echo $navigationsTextColor ?>;text-decoration:none;position:relative;display:inline-block}
.acc-cwrap .skip-link:hover{text-decoration:none;color:<?php echo $navigationsTextColor  ?> }
.acc-cwrap .skip-link:hover .icon{color:<?php echo $navigationsTextColor  ?>}
.acc-cwrap .skip-cart .icon:before{content:"\e900"}
.acc-cwrap .skip-account .icon:before{content:"\e901";font-size:23px}
.acc-cwrap .skip-search .icon:before{content:"\e903";font-size:19px}
.acc-cwrap .skip-cart:hover .icon{background-position:-50px -95px}
.acc-cwrap .skip-link .links{background:#FBFBFB;border:solid 1px #cccccc;display:none;position:absolute;z-index:200;top:30px;left:0;width:200px;padding:5px 0}
.acc-cwrap .skip-link:hover .links{display:block}
.acc-cwrap .skip-link .links a{position:relative;display:block;padding:5px 10px;line-height:23px;text-align:center;color:#636363}

@media (max-width:770px){
.acc-cwrap{display:none}
}

.skip-links{clear:both;border-top:1px solid #EDEDED;position:relative;min-height:42px}
@media (min-width:771px){
.skip-links{border:0;display:none}
}

.skip-links .skip-link{float:left;width:33.3%;color:<?php echo $navigationsTextColor ?>;line-height:42px;text-align:center;border-bottom:1px solid #EDEDED;box-sizing:border-box}
.dir-rtl .skip-links .skip-link{float:right}
.skip-links.links-4 .skip-link{width:25%}
.skip-links .skip-link a,.skip-links .skip-link>span{display:inline-block;line-height:42px;width:100%;color:<?php echo $navigationsTextColor ?>;box-sizing:border-box}
.skip-links .skip-link:hover{background:#EDEDED;color:inherit}
.skip-links .skip-link a:hover,.skip-links .skip-link>span:hover{text-decoration:none;cursor:pointer}
.skip-links .skip-link ul a,.skip-links .skip-link ol a{padding:0 15px 0 25px;text-align:left}
.dir-rtl .skip-links .skip-link ul a,.dir-rtl .skip-links .skip-link ol a{text-align:right;padding:0 25px 0 15px}
.skip-links .skip-link #nav,.skip-links .skip-link .links{display:none;position:absolute;z-index:100;background:#EDEDED;width:100%;left:0;top:42px}
.skip-links .skip-link:hover #nav,.skip-links .skip-link:hover .links{display:block}
@media (max-width:770px){
.nav-primary{overflow:hidden}
.skip-links .skip-link{border-right:1px solid #EDEDED;overflow:hidden}
.dir-rtl .skip-links .skip-link{border-right:0;border-left:1px solid #EDEDED}
.skip-links .skip-link a,.skip-links .skip-link>span{white-space: nowrap}
#nav .nav-primary li.parent:hover > a:after{content:'';position:absolute;width:0;height:0;display:block;border-right:5px solid transparent;border-left:5px solid transparent;border-top:5px solid #cccccc;border-bottom:none;top:50%;left:10px;right:auto;margin-top:-5px}
.dir-rtl #nav .nav-primary li.parent:hover > a:after{border-right:5px solid transparent;border-left:5px solid transparent;border-top:5px solid #cccccc;border-bottom:none;top:50%;right:10px;left:auto}
#nav .nav-primary li.parent > a:after{content:'';position:absolute;width:0;height:0;display:block;border-top:5px solid transparent;border-bottom:5px solid transparent;border-left:5px solid #cccccc;border-right:none;top:50%;left:10px;right:auto;margin-top:-5px}
.dir-rtl #nav .nav-primary li.parent > a:after{border-left:none;border-right:5px solid #cccccc;top:50%;right:10px;left:auto;margin-top:-5px}
#nav li.level0 ul{height:0;overflow:hidden;padding-left:25px;position:relative}
.dir-rtl #nav li.level0 ul{padding:0 25px 0 0}
#nav li.level0 ul:before{content:"";display:block;position:absolute;width:100%;height:100%;min-height:500px;left:0;z-index:100;transition:all 1s 0s;visibility:visible}
#nav .nav-primary li:hover > ul{height:auto;overflow:visible;transition:overflow 1s 0s;box-sizing:border-box}
#nav .nav-primary li:hover > ul:before{visibility:hidden}
.nav-primary li.level0 li{padding:0 0 0 25px;box-sizing:border-box}
.dir-rtl .nav-primary li.level0 li{padding:0 25px 0 0}
.skip-links .skip-link ul li a,.skip-links .skip-link ol li a{border-bottom:1px solid #cccccc}
.skip-links .skip-link ul li:last-child a:hover,.skip-links .skip-link ol li:last-child a:hover{background-color:#f4f4f4;text-decoration:none}
.skip-links .skip-link:last-child{border-right:0}
}

.skip-link .icon{display:inline-block;width:30px;height:30px;vertical-align:middle;color:<?php echo $navigationsTextColor ?>}
.skip-link .icon:before{display:inline-block;vertical-align:top;width:30px;height:30px;line-height:30px;text-align:center}
.skip-link .icon:hover{color: <?php echo $navigationsTextColor ?>}
.skip-links .skip-link .skip-nav .icon:before{content:"\e902";font-size:19px}
.skip-links .skip-link .skip-account .icon:before{content:"\e901";font-size:23px}
.skip-links .skip-link .skip-search .icon:before{content:"\e903";font-size:18px}
.skip-links .skip-link .skip-cart .icon:before{content:"\e900"}

.breadcrumbs{overflow:hidden;margin:-15px 0 15px 0}
.breadcrumbs li{float:left;font-size:12px;font-family:"Raleway","Helvetica Neue",Verdana,Arial,sans-serif;text-transform:uppercase}
.breadcrumbs a{float:left;color:<?php echo $linkColor ?>}
.breadcrumbs a:hover{color:<?php echo $linkColorHover ?>}
.breadcrumbs strong{color:<?php echo $linkColor ?>;font-weight:normal}
.breadcrumbs span{float:left;padding:0 7px}
.dir-rtl .breadcrumbs li{float:right}
.dir-rtl .breadcrumbs a{float:right}
@media (max-width:770px){
.breadcrumbs{display:none}
}
@media (max-width:500px){
.skip-links.links-4 .skip-link:first-child{width:34%}
.skip-links.links-4 .skip-link{width:22%}
.links-4 .skip-link a .label{display:none}
}

.messages{margin-bottom:10px}
.col-main .messages li{margin:0;width:100%;padding:7px 10px 7px 0;text-align:left}
.col-main .messages li li{position:relative;margin-bottom:5px;padding:7px 10px 7px 20px;background:#f4f4f4;font-size:15px}
.messages li li:before{top:50%;left:0;margin-top:-6px}
.messages .error-msg li{color:#000;border-left:5px solid #df280a;background-color:#faebe7}
.messages .error-msg li:before{content:'';position:absolute;width:0;height:0;display:block;border-top:6px solid transparent;border-bottom:6px solid transparent;border-left:6px solid #df280a;border-right:none}
.messages .notice-msg li{color:#000;border-left:5px solid #e26703;background-color:#f9ebe6}
.messages .notice-msg li:before{content:'';position:absolute;width:0;height:0;display:block;border-top:6px solid transparent;border-bottom:6px solid transparent;border-left:6px solid #e26703;border-right:none}
.messages .success-msg li{color:#000;border-left:5px solid #11b400;background-color:#eff5ea}
.messages .success-msg li:before{content:'';position:absolute;width:0;height:0;display:block;border-top:6px solid transparent;border-bottom:6px solid transparent;border-left:6px solid #11b400;border-right:none}

.main-container{padding:30px;position:relative}
.main-container:before,.main-container:after{content:"";display:block;clear:both}
@media (max-width:640px){
.main-container{padding:10px 15px}
}

.footer-container{padding:0 30px}
.footer{width:100%;border-top:1px solid #cccccc;padding-top:15px;text-align:center;font-size:12px}
.footer address{border-top:1px solid #cccccc;text-align:center;width:100%;font-size:11px;margin-top:15px;padding:20px 0}
.footer li{display:inline-block;padding:0 10px}
@media (max-width:640px){
.footer-container{padding:0 15px}
}