<?php
/**
 * Created by PhpStorm.
 * User: svatoslavzilicev
 * Date: 05.08.16
 * Time: 19:45
 */
?>
<?php if ($_COOKIE['redirected']): ?>
<script type="text/javascript">
        jQuery(document).ready(function () {
            if (Mage.Cookies.get('redirectPop') != 'shown') {
                jQuery.fancybox({
                    'padding': '0px',
                    'autoScale': true,
                    'transitionIn': 'fade',
                    'transitionOut': 'fade',
                    'type': 'inline',
                    'href': '#redirectPop',
                    'onComplete': function () {
                        Mage.Cookies.set('redirectPop', 'shown');
                    },
                    'tpl': {
                        closeBtn: '<a title="Close" class="fancybox-item fancybox-close fancybox-newsletter-close" onclick="setcookieshown()" href="javascript:;"></a>'
                    }
                });
                jQuery('#redirectPop').trigger('click');
            }
        });

    function setcookieshown() {
        Mage.Cookies.set('redirectPop', 'shown');
    }
</script>
<div class="redirect-popup" id="redirectPop">
    <div class="block-content">
            <div class="popuptexttop" style="margin-top: 100px; margin-left: 140px; margin-right: 140px">
                <div style="font-size: 40px; color: #464a4e; text-transform: uppercase">Guess What??</div>
                <div style="font-size: 40px; color: #464a4e; text-transform: uppercase; margin-top: 3px;">We've moved places!</div>
            </div>
            <div class="popuptextbot" style="margin-top: 20px;">
                <div style="font-size: 17px; color: #464a4e;">Check out our new site and let us know what you think,</div>
                <div style="font-size: 17px; color: #464a4e; margin-top: 10px;">and while you're at it - Here's a $20 voucher</div>
                <div style="font-size: 17px; color: #464a4e; margin-top: 10px">to say thank you.</div>
            </div>
            <div class="popuptextbotbot" style="background-color: #05b59d; padding: 30px 0; text-align: center; width: 100%; margin-top: 25px;">
                <div style="color: white; font-size: 21px">Please use voucher code: BWOLOYALTY</div>
            </div>
            <div class="popupimagesbot" style="display: flex;
    justify-content: space-between; background-color: #464a4e;">
                <div class="popupcas" style="display: inline-block;background: url('<?php echo $this->getSkinUrl('images/popupcasioBg.jpg') ?>') no-repeat; height: 85px; width: 341px"></div>
                <div class="popupbwo" style="display: inline-block;background: url('<?php echo $this->getSkinUrl('images/popupbwoBg.jpg') ?>') no-repeat;height: 85px; width: 341px "></div>
            </div>
    </div>
</div>
<?php endif; ?>