<?php
/**
  Made by Smartwave.
 */
?>
<?php
$store = Mage::app()->getStore();
$code = $store->getCode();
$footer = Mage::getStoreConfig('porto_settings/footer', $code);
?>
<div class="block block-subscribe">
    <div class="block-title">
        <strong><span><?php echo $footer['footer_newsletter_title']; ?></span></strong>
    </div>
    <form method="post" action-xhr="<?php echo $this->getFormActionUrl() ?>" id="footer-newsletter-validate-detail" target="_top">
        <div class="block-content">
            <p><?php echo $footer['footer_newsletter']; ?></p>
            <div class="input-box">
                <p class="label"><?php echo $this->__('Enter your e-mail Address'); ?></p>
                <input type="text" name="email" id="newsletter_footer" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" />
                <input type="hidden" name="action" id="action" value="<?php echo $this->getFormActionUrl() ?>" />
                <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                <div class="clearer"></div>
            </div>
        </div>
    </form>
</div>